name: Cypress NewTests

on:
  push:
  schedule:
    - cron: "0 8 * * 1,3,4,5"
    - cron: "0 20 * * 1,3,4,5"
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
