name: Cypress NewTests

on:
  schedule:
    - cron: "40 22 * * 1,5"
    - cron: "50 22 * * 1,5"
    - cron: "00 21 * * 1,5"
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
      -name: Read Json File
       run: | 
          echo: jsonfile: ${'../fixtures/datatest.json'}


